# Best Auction Configuration

# Language Settings
# Available languages: en, ja
language: "ja"

# Database Settings
database:
  type: "sqlite"  # sqlite, mysql
  host: "localhost"
  port: 3306
  database: "best_auction"
  username: ""
  password: ""
  
# Auction Settings
auction:
  # Default auction duration in hours
  default_duration: 24
  
  # Maximum auction duration in hours
  max_duration: 168  # 7 days
  
  # Minimum auction duration in hours
  min_duration: 1
  
  # Listing fee percentage (0.05 = 5%)
  listing_fee_rate: 0.05
  
  # Minimum listing fee
  min_listing_fee: 10
  
  # Maximum listing fee
  max_listing_fee: 1000
  
  # Auction house tax percentage (0.03 = 3%)
  tax_rate: 0.03

# UI Settings
ui:
  # Items per page in auction house
  items_per_page: 45
  
  # Max search results to display
  max_search_results: 100

# Mail Settings
mail:
  # Maximum mail storage per player
  max_mail_per_player: 50
  
  # Auto-delete mail after days (0 = never)
  auto_delete_days: 30

# Permission Settings
permissions:
  # Require permission to use auction house
  require_permission: false
  
  # Base permission node
  base_permission: "bestauction.use"