# Best Auction Configuration

# Language Settings
# Available languages: en, ja
language: "ja"

# Database Settings
database:
  type: "sqlite"  # sqlite, mysql
  host: "localhost"
  port: 3306
  database: "best_auction"
  username: ""
  password: ""
  
# Auction Settings
auction:
  # Default auction duration in hours (current: 9 days 12 hours = 228 hours)
  default_duration: 228
  
  # Listing fee percentage (0.05 = 5%)
  listing_fee_rate: 0.05
  
  # Minimum listing fee
  min_listing_fee: 10
  
  # Maximum listing fee
  max_listing_fee: 1000
  
  # Auction house tax percentage (0.03 = 3%)
  tax_rate: 0.03
  
  # Stack quantity limits
  # If true, allow any quantity to be listed
  # If false, limit to 1 or max stack size (typically 64)
  allow_any_stack_quantity: false
  
  # Player listing limits
  # Maximum number of items a player can list simultaneously
  max_player_listings: 7

# Currency Settings
currency:
  # Use Vault for currency formatting (recommended)
  use_vault_format: true
  
  # Fallback currency name (used when Vault is unavailable)
  fallback_currency: "gil"
  
  # Currency symbol (used when use_vault_format is false)
  currency_symbol: ""

# UI Settings
ui:
  # Items per page in auction house
  items_per_page: 45
  
  # Max search results to display
  max_search_results: 100
  
  # Date format for auction expiry display
  # Examples: "yyyy-MM-dd", "MM/dd/yyyy", "dd/MM/yyyy", "yyyy年MM月dd日"
  date_format: "yyyy-MM-dd"

# Mail Settings
mail:
  # Maximum mail storage per player
  max_mail_per_player: 50
  
  # Auto-delete mail after days (0 = never)
  auto_delete_days: 30

# Permission Settings
permissions:
  # Require permission to use auction house
  require_permission: false
  
  # Base permission node
  base_permission: "bestauction.use"

# Debug Settings
debug:
  # Enable debug commands (testdata, etc.)
  # WARNING: Only enable in development/testing environments
  enable_debug_commands: false

# Cloud Integration Settings
cloud:
  # Enable cloud event reporting
  enabled: false
  
  # Cloudflare Workers base URL
  base_url: "https://best-auction-cloud.masafumi-t.workers.dev"
  
  # API token for authentication (REQUIRED - obtain from cloud dashboard)
  api_token: ""
  
  # Server identifier (used to distinguish multiple servers)
  server_id: "default-server"
  
  # Authentication settings
  auth:
    # Auto-validate token on startup
    validate_on_startup: true
    
    # Re-validate token interval (in minutes, 0 = disabled)
    revalidate_interval: 60
  
  # Data synchronization settings
  sync:
    # Auto-sync existing data on first startup (when token is valid)
    auto_sync_on_startup: true
    
    # Batch size for initial data sync (number of auctions per request)
    batch_size: 50
    
    # Delay between batch requests in milliseconds
    batch_delay: 1000
    
    # Sync existing bids along with auctions
    include_bids: true
    
    # Force full resync (ignores last sync timestamp)
    force_full_sync: false
  
  # HTTP request timeout in milliseconds
  timeout: 5000
  
  # Number of retry attempts for failed requests
  retry_attempts: 3
  
  # Delay between retry attempts in milliseconds
  retry_delay: 1000
  
  # Events to send to cloud (can disable specific events)
  events:
    item_listed: true
    bid_placed: true
    bid_cancelled: true
    auction_cancelled: true
    item_sold: true