name: best_auction
version: '1.0-SNAPSHOT'
main: com.hacklab.best_auction.Main
api-version: '1.20'
authors: [ masafumi terazono ]
softdepend: [ Vault ]

commands:
  auction:
    description: Main auction house command
    usage: /auction [help|sell|bid|cancel|search|mail|testdata]
    aliases: [ ah ]

permissions:
  auction.admin:
    description: Admin permissions for auction commands
    default: op
  auction.use:
    description: Basic auction usage permissions
    default: true
