name: Deploy to Modrinth

on:
  push:
    tags:
      - 'v*'  # Triggers on tags starting with 'v' (e.g., v1.0.0, v1.1.0)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build plugin
      run: ./gradlew clean shadowJar
      
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Get changelog
      id: changelog
      run: |
        # Extract changelog for this version (customize as needed)
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "🎉 New release v${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "## Changes" >> $GITHUB_OUTPUT
        echo "- Latest improvements and bug fixes" >> $GITHUB_OUTPUT
        echo "- Enhanced auction system features" >> $GITHUB_OUTPUT
        echo "- Performance optimizations" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "For detailed changes, see the commit history." >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Upload to Modrinth
      env:
        MODRINTH_PROJECT_ID: ${{ secrets.MODRINTH_PROJECT_ID }}
        MODRINTH_PAT: ${{ secrets.MODRINTH_PAT }}
      if: env.MODRINTH_PROJECT_ID != '' && env.MODRINTH_PAT != ''
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        # Modrinth configuration
        modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
        modrinth-token: ${{ secrets.MODRINTH_PAT }}
        
        # File configuration
        files: |
          build/libs/best_auction-*-all.jar
          
        # Project information
        name: Best Auction v${{ steps.version.outputs.VERSION }}
        version: ${{ steps.version.outputs.VERSION }}
        version-type: release  # release, beta, or alpha
        
        # Changelog
        changelog: ${{ steps.changelog.outputs.CHANGELOG }}
        
        # Game versions (adjust as needed)
        game-versions: |
          1.20.6
          1.20.5
          1.20.4
          1.20.1
          
        # Mod loaders
        loaders: |
          paper
          spigot
          
        # Dependencies
        dependencies: |
          vault(optional)
          
        # Java version requirement
        java: 17
        
        # Project links
        retry-attempts: 2
        retry-delay: 10000
        fail-mode: fail